title: Ice Cubes
email: christinewinter1@gmx.de
description: >- # this means to ignore newlines until "baseurl:"
  A Winter Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.christinewinter.se" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  christinewinter

# Build settings
markdown: kramdown
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
